# Generated by Django 3.2.16 on 2024-06-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='related_post',
        ),
    ]
