# Generated by Django 3.2.16 on 2024-06-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_post_comment_related_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='related_post',
            new_name='post',
        ),
    ]
