# Generated by Django 3.2.16 on 2024-07-01 15:55

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_related_post_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='Если установить дату и время в будущем — можно делать отложенные публикации.', validators=[blog.validators.real_date], verbose_name='Дата и время публикации'),
        ),
    ]
